Update deps
go get -u ./...
go mod tidy

Also fix breaking change in http signing:
```
pkg/runner/aggregate_sender.go:52:3: too many arguments in call to httpsign.NewP256Signer
	have (string, ecdsa.PrivateKey, *httpsign.SignConfig, httpsign.Fields)
	want (ecdsa.PrivateKey, *httpsign.SignConfig, httpsign.Fields)
```